### PR TITLE
Added responsiveness to UI

### PR DESCRIPTION
**Pull request by AniVerma17**
UI update for mobile responsiveness

### CODE REVIEW

**Comment by thisisayush** [comment]
Please add screenshots or include a working demo. It'll be really helpful :)

**Comment by AniVerma17** [comment]
Demo on https://aniverma17.github.io/geekbattle/

**Comment by thisisayush** [comment]
The ALiAS Logo seems to overlap the event logo.

**Comment by AniVerma17** [comment]
That's done on purpose....that much overlap doesn't do any harm.
Will change if majority review says to.

**Pull request closed without merging**
